"""Born-digital formula candidates from PDF structure facts.

This module reuses the MuPDF glyph/span/vector evidence layer.  It does not
invoke OCR/MFR and does not infer formulas from sample-specific text patterns.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from typing import Any

import fitz

from src.core.born_digital_math import (
    BornDigitalMathAuditor,
    BornDigitalPage,
    MuPDFBornDigitalExtractor,
)
from src.core.pdf_glyph_graph import RawGlyphGraphExtractor


@dataclass(frozen=True)
class BornDigitalFormulaCandidate:
    """One structure-backed formula candidate."""

    candidate_id: str
    page_num: int
    bbox: tuple[float, float, float, float]
    text: str
    latex: str
    confidence: float
    input_hash: str
    evidence: dict[str, Any]
    warnings: tuple[str, ...]
    model: str = "pymupdf_born_digital_structure"
    model_version: str = "pymupdf_rawdict_facts_v1"
    preprocess_version: str = "glyph-vector-json-v1"


class BornDigitalFormulaStructureExtractor:
    """Extract r0 formula candidates from born-digital PDF structure."""

    def __init__(self, min_confidence: float = 0.5) -> None:
        self._min_confidence = float(min_confidence)
        self._extractor = MuPDFBornDigitalExtractor()
        self._auditor = BornDigitalMathAuditor()
        self._graph_extractor = RawGlyphGraphExtractor(self._extractor)

    def extract_page(
        self,
        page: fitz.Page,
        page_num: int,
        existing_ids: set[str] | None = None,
    ) -> list[BornDigitalFormulaCandidate]:
        page_facts = self._extractor.extract_page(page, page_num)
        return self.extract_candidates_from_page_facts(page_facts, existing_ids=existing_ids)

    def extract_candidates_from_page_facts(
        self,
        page_facts: BornDigitalPage,
        existing_ids: set[str] | None = None,
    ) -> list[BornDigitalFormulaCandidate]:
        raw_graph = self._graph_extractor.from_page_facts(page_facts)
        regions = self._auditor.display_formula_regions(page_facts)
        try:
            diagnostics = {
                diagnostic.bbox: diagnostic.to_json()
                for diagnostic in self._auditor.region_diagnostics(page_facts, regions)
            }
        except Exception:
            diagnostics = {}
        existing_ids = set(existing_ids or set())
        candidates: list[BornDigitalFormulaCandidate] = []
        for index, region in enumerate(regions):
            confidence = float(region.confidence)
            warnings: set[str] = set()
            if confidence < self._min_confidence:
                warnings.add("low_confidence")
            if not region.text.strip():
                warnings.add("empty_pdf_text")
            candidate_id = f"p{page_facts.page_num}_r0_{index}"
            suffix = 1
            while candidate_id in existing_ids:
                candidate_id = f"p{page_facts.page_num}_r0_{index}_{suffix}"
                suffix += 1
            existing_ids.add(candidate_id)
            evidence = {
                "page_num": page_facts.page_num,
                "bbox": region.bbox,
                "source": region.source,
                "region": region.to_json(),
                "raw_glyph_graph": {
                    "schema_version": raw_graph.schema_version,
                    "input_hash": raw_graph.input_hash,
                    "health": raw_graph.health.__dict__,
                    "glyphs": [
                        glyph.__dict__
                        for glyph in raw_graph.glyphs
                        if _bbox_intersects(glyph.bbox, region.bbox)
                    ],
                    "vectors": [
                        vector.__dict__
                        for vector in raw_graph.vectors
                        if _bbox_intersects(vector.bbox, region.bbox)
                    ],
                    "images": [
                        image.__dict__
                        for image in raw_graph.images
                        if _bbox_intersects(image.bbox, region.bbox)
                    ],
                },
                "diagnostics": diagnostics.get(region.bbox, {}),
                "note": "r0 stores born-digital PDF facts only; high-precision LaTeX is generated by later tool/model candidate rounds.",
            }
            input_hash = self._input_hash(evidence)
            candidates.append(
                BornDigitalFormulaCandidate(
                    candidate_id=candidate_id,
                    page_num=page_facts.page_num,
                    bbox=region.bbox,
                    text=region.text,
                    latex=region.text,
                    confidence=confidence,
                    input_hash=input_hash,
                    evidence=evidence,
                    warnings=tuple(sorted(warnings)),
                )
            )
        return candidates

    @staticmethod
    def _input_hash(evidence: dict[str, Any]) -> str:
        payload = json.dumps(evidence, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(payload.encode("utf-8", errors="ignore")).hexdigest()


def _bbox_intersects(
    left: tuple[float, float, float, float],
    right: tuple[float, float, float, float],
) -> bool:
    return left[0] <= right[2] and left[2] >= right[0] and left[1] <= right[3] and left[3] >= right[1]
